config/routes.rb
Rails.application.routes.draw do

  resources :jobs do
    resources :apply_jobs
  end
  #company

  resources :companies do
    resources :reviews
  end
  #users
  devise_for :users

  #static pages routes
  root 'static_pages#home'
  get 'static_pages/about'
  get 'static_pages/contact'

  resources :user_info, only: [:new, :create]
  
  match '*path', to: 'static_pages#home', via: :all
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/job.rb
class Job < ApplicationRecord
  belongs_to :company
  has_many :apply_jobs

  def self.search_job(search_params)
  	if search_params["company_name"].present?
  		company_name = Company.where("name like ?", "%#{search_params["company_name"]}%")
  		jobs = company_name.map{|a| a.jobs.where("title like ?", "%#{search_params["job_title"]}%")}[0] if (company_name.present? and search_params["job_title"].present?)
      jobs.present? ? jobs  : company_name.map{|a| a.jobs }[0]
  	else
  		self.where("title like ?", "%#{search_params["job_title"]}%")
  	end
  end

end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_company, except: [:index, :show]
  before_action :set_job, only: [ :edit, :update, :destroy]
  before_action :check_current_user_applied_for_this_job, only: [:show]


  def index
    @search_params = params[:search]
    if @search_params.present?
      @jobs = Job.search_job(@search_params)
    else
      @jobs = Job.all
    end
    respond_to do |format|
      format.html
      format.json
    end

  end

  def show
    @job = Job.includes(:apply_jobs).find(params[:id])
    #nil.test!
    respond_to do |format|
      format.html
      format.json
    end
  end

  # GET /jobs/new
  def new
    @job = Job.new
  end

  # GET /jobs/1/edit
  def edit
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = @company.jobs.new(job_params)

    respond_to do |format|
      if @job.save
        format.html { redirect_to @job, notice: 'Job was successfully created.' }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1
  # PATCH/PUT /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to @job, notice: 'Job was successfully updated.' }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to jobs_url, notice: 'Job was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private


    def set_company
      #nil.test!
      if current_user.job_seeker?
        redirect_to jobs_path
      else
        if current_user.company.present?
          @company = current_user.company
        else
          flash[:notice] = 'Please create company'
          redirect_to new_company_path
        end
      end
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    def check_current_user_applied_for_this_job
      return unless user_signed_in? 
      @job_applied = ApplyJob.job_applied(current_user.id, params["id"].to_i)
    end

    # Only allow a list of trusted parameters through.
    def job_params
      params.require(:job).permit(:title, :description, :company_id, :location, :salary, :skills)
    end
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_form.html.erb
    <%= form_with(model: job, local: true) do |form| %>

      <div class="form-group">
        <%= form.text_field :title, class: "form-control", placeholder: "Job Title" %>
      </div>

      <div class="form-group">
        <%= form.text_area :description, class: "form-control", placeholder: "Job Description" %>
      </div>

      <div class="form-group">
        <%= form.text_field :location, class: "form-control", placeholder: "Job Location" %>
      </div>

      <div class="form-group">
        <%= form.text_field :salary, class: "form-control", placeholder: "Salary Ex: 5LPA , 10LPA ... etc" %>
      </div>

      <div class="form-group">
        <%= form.text_field :skills, class: "form-control", placeholder: "Skills ex: c, c++, java ... etc" %>
      </div>

      <div class="form-group">
        <%= form.submit :submit, class: "btn btn-primary" %>
      </div>
    <% end %>

app/views/jobs/edit.html.erb
<div class="row text-center">
  <h3>Edit Job</h3>
</div>

<br>
<br>
<div class="row">
  <div class="col-md-4 col-md-offset-4">
	<%= render 'form', job: @job %>
  </div>
</div>

app/views/jobs/index.html.erb
<div class="row text-center">
  <h1>List of Jobs</h1>
</div>

<br>
<br>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
  	<%= form_for :search, url: jobs_path, method: :get do |f| %>

  		<div class="row">
  			<div class="col-md-5">
  				<%= f.text_field :job_title, value: @search_params.present?? @search_params["job_title"] : "" , class: "form-control", placeholder: "Job Title" %>
  			</div>
  			<div class="col-md-5">
  				<%= f.text_field :company_name, value: @search_params.present?? @search_params["company_name"] : "", class: "form-control", placeholder: "Company name" %>
  			</div>
  			<div class="col-md-2">
  				<%= f.submit "Search", class: "btn btn-primary" %>
  			</div>
  		</div>

  	<% end %>
  </div>
</div>
<br>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
  	<% if @jobs.present? %>
	    <% @jobs.each do |job| %>
	      <h3><%= link_to job.title, job_path(job) %></h3>
	      <p><strong>Company: </strong><%= job.company.name %> &emsp; <strong>Location:</strong> <%= job.location %></p>
	    <% end %>
	<% else %>
		<br>
		<p class="row text-center">
			No jobs found
		</p>
	<% end %>
  </div>
</div>

app/views/jobs/new.html.erb
<div class="row text-center">
  <h3>Create Job</h3>
</div>

<br>
<br>
<div class="row">
  <div class="col-md-4 col-md-offset-4">
	<%= render 'form', job: @job %>
  </div>
</div>

app/views/jobs/show.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h1><%= @job.title %></h1>
    <br>
    <p><strong>Company Name: </strong> <%= @job.company.name %></p>
    <p><strong>Location: </strong> <%= @job.location %></p>
    <p><strong>Salary: </strong> <%= @job.salary %></p>
    <br>
    <p><strong>Skills: </strong> <%= @job.skills %></p>
    <br>
    <p>
      <%= @job.description %>
    </p>
    <br>
    <p>
      <%= @job.apply_job_ids.length %> people applied
    </p>
    <p>
      <% if user_signed_in? %>
        <% if @job_applied.present? %>
          <%= link_to "Applied", new_job_apply_job_path(job_id: @job.id), class: "btn btn-primary disabled" %>
        <% else %>
          <%= link_to "Apply", new_job_apply_job_path(job_id: @job.id), class: "btn btn-primary " %>
        <% end %>
      <% else %>
        <%= link_to "Apply (Please sign in)", new_job_apply_job_path(job_id: @job.id), class: "btn btn-primary disabled" %>
      <% end %>
    </p>
  </div>
</div>