config/routes.rb
Rails.application.routes.draw do

  resources :jobs do
    resources :apply_jobs
  end
  #company

  resources :companies do
    resources :reviews
  end
  #users
  devise_for :users

  #static pages routes
  root 'static_pages#home'
  get 'static_pages/about'
  get 'static_pages/contact'

  resources :user_info, only: [:new, :create]
  
  match '*path', to: 'static_pages#home', via: :all
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/company.rb
class Company < ApplicationRecord
  belongs_to :user
  has_many :jobs
  has_many :reviews, as: :reviewable
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
	before_action :authenticate_user!, except: [:index, :show]
	before_action :company_params, only: [:create]

	def index
		@companies = Company.includes(:reviews).all
	end

	def show
		@company = Company.includes(:reviews).find(params[:id])
	end

	def new
		@company = Company.new
	end

	def create
		@company = current_user.build_company(company_params)
		#nil.test!
		#nil.test!
		if @company.save!
			flash[:notice] = "company is created"
			redirect_to new_job_path
		else
			flash[:error] = "Something went wrong"
			render :new
		end
	end

	private

	def company_params
		params.require(:company).permit(:name, :description, :user_id, :location, :emp_count)
	end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/index.html.erb
<div class="row text-center">
  <h3>List of Companies</h3>
</div>
<br>
<br>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
  	<% @companies.each do |c| %>
  		<div class="border_bottom">
  			<h3><%= link_to c.name, company_path(c) %></h3>
  			<p><strong>Emp Count:</strong> <%= c.emp_count %></p>
  			<p><%= link_to "List Of Jobs", "" %> </p>
        <p>Reviews count: <%= c.reviews.count %></p>
  		</div>
  	<% end %>
  </div>
</div>

app/views/companies/new.html.erb
<div class="row text-center">
  <h3>Company create</h3>
</div>
<br>
<br>
<div class="row">
  <div class="col-md-4 col-md-offset-4">
  	<%= form_for @company, method: :post do |f| %>

  		<div class="form-group">
  			<%= f.text_field :name, class: "form-control", placeholder: "Company name" %>
  			<%= f.hidden_field :user_id, value: current_user.id %>
  		</div>

  		<div class="form-group">
  			<%= f.text_area :description, class: "form-control", placeholder: "Company description" %>
  		</div>
  		<div class="form-group">
  			<%= f.text_field :location, class: "form-control", placeholder: "Location" %>
  		</div>
  		<div class="form-group">
  			<%= f.text_field :emp_count, class: "form-control", placeholder: "Ex: 5-20. 50-100" %>
  		</div>
  		<div class="form-group">
  			<%= f.submit :submit, class: "btn btn-primary" %>
  		</div>

  	<% end %>
  </div>
</div>

app/views/companies/show.html.erb
<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<h1><%= @company.name %></h1>
		<br>
		<p>Location: <%= @company.location %></p>
		<p>Employees: <%= @company.emp_count %></p>
		<br>
		<p>
			<%= @company.description %>
		</p>

	</div>
</div>
<br>
<br>
<br>
<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<% @company.reviews.each do |r| %>
			<p>Reviewed by <%= r.user.email.split("@")[0] %>, <%= r.role %></p>
			<p><%= r.body %></p>
		<% end %>
	</div>
</div>
<br>
<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<%= form_for :review, url: company_reviews_path(company_id: params[:id]), method: :post do |f| %>
			<div class="form-group">
				<%= f.text_area :body, class: "form-control", placeholder: "Review" %>
			</div>

			<div class="form-group">
				<%= f.text_field :role, class: "form-control", placeholder: "Role" %>
			</div>

			<div class="form-group">
				<%= f.submit :submit, class: "btn btn-primary" %>
			</div>
		<% end %>
	</div>
</div>