config/routes.rb
Rails.application.routes.draw do

  resources :jobs do
    resources :apply_jobs
  end
  #company

  resources :companies do
    resources :reviews
  end
  #users
  devise_for :users

  #static pages routes
  root 'static_pages#home'
  get 'static_pages/about'
  get 'static_pages/contact'

  resources :user_info, only: [:new, :create]
  
  match '*path', to: 'static_pages#home', via: :all
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/apply_job.rb
class ApplyJob < ApplicationRecord
  belongs_to :user
  belongs_to :job

  def self.job_applied(user, job)
  	where('user_id like ? and job_id like ?', user, job)
  end
end

app/controllers/apply_jobs_controller.rb
class ApplyJobsController < ApplicationController
	before_action :set_a_job, only: [:new, :create]
	before_action :apply_job_params, only: [:create]
  def index
  end

  def show
  end

  def new
  	@apply_job = ApplyJob.new
  end
  
  def create
  	@apply_job = @job.apply_jobs.new(apply_job_params)
  	@apply_job.user_id = current_user.id
  	if @apply_job.save!
  		flash[:notice] = "Job applied"
  		redirect_to job_path(@job)
  	else
  		flash[:notice] = "Something went wrong"
  		redirect_to job_path(@job)
  	end
  end

  private

  def set_a_job
  	@job = Job.find(params[:job_id])
  end

  def apply_job_params
  	params.require(:apply_job).permit(:name, :ctc, :ectc, :notice_period, :exp)
  end


end

app/helpers/apply_jobs_helper.rb
module ApplyJobsHelper
end

app/views/apply_jobs/create.html.erb
<h1>ApplyJobs#create</h1>
<p>Find me in app/views/apply_jobs/create.html.erb</p>

app/views/apply_jobs/index.html.erb
<h1>ApplyJobs#index</h1>
<p>Find me in app/views/apply_jobs/index.html.erb</p>

app/views/apply_jobs/new.html.erb
<div class="row text-center">
  <h3>Apply Job</h3>
</div>

<br>
<br>
<div class="row">
	<div class="col-md-4 col-md-offset-4">
		<h4><%= @job.title %> - <%= @job.company.name %></h4>
	</div>
</div>

<br>
<br>

<div class="row">
  <div class="col-md-4 col-md-offset-4">
	<%= form_for :apply_job, url: job_apply_jobs_path(@job.id), method: :post do |f| %>
		<div class="form-group">
			<%= f.text_field :name , class: "form-control", placeholder: "Name"%>
		</div>
		<div class="form-group">
			<%= f.number_field :exp , class: "form-control", placeholder: "Experience"%>
		</div>
		<div class="form-group">
			<%= f.text_field :ctc , class: "form-control", placeholder: "CTC ex: 5LPA"%>
		</div>
		<div class="form-group">
			<%= f.text_field :ectc , class: "form-control", placeholder: "ECTC ex: 10LPA"%>
		</div>
		<div class="form-group">
			<%= f.text_field :notice_period , class: "form-control", placeholder: "Notice Period"%>
		</div>

		<div class="form-group">
			<%= f.submit  "Apply", class: "btn btn-primary" %>
		</div>
	<% end %>
  </div>
</div>

app/views/apply_jobs/show.html.erb
<h1>ApplyJobs#show</h1>
<p>Find me in app/views/apply_jobs/show.html.erb</p>